image:
  registry: hub.example.com
  repository: esleirter/go-gin-api
  tag: v0.0.0
  pullPolicy: IfNotPresent

imagePullSecrets: []
  # - hub_gdpteam_com_secret
nameOverride: ""
fullnameOverride: ""

replicaCount: 1

serviceAccount:
  create: true
  annotations: {}
  name:

podSecurityContext: {}

securityContext: {}

containerPort: 3000

livenessProbe:
  enabled: false

readinessProbe:
  enabled: false

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

envVars:
  GDP_API_PORT: "3000"

extraEnvVars: []
  # - name: FOO
  #   value: "var"

extraEnvVarsSecret: ""

extraVolumeMounts: []

extraVolumes: []

resources:
  limits:
    cpu: 500m
    memory: 250Mi
  requests:
    cpu: 500m
    memory: 250Mi

nodeSelector: {}

tolerations: []

affinity: {}
